### ISSUE TITLE
Crash on Startup - Fabric 1.21

### ISSUE THREAD

**Issue by Morizera** [ryankshah/skyrimcraft-multiloader#2]
Game just don't open at all. I'm using only fabric api and skyrimcraft at all. I'll leave here more information and prints;

Steps to reproduce crash:
1- download and install skyrimcraft with geckolib, common network and dragon shouts, as well fabric loader 1.21 0.16.7 and fabric api 0.102.0+1.21;
2- try to open the game.

![crash](https://github.com/user-attachments/assets/2f476d12-c59f-46f2-b435-f0572771f9bb)
[latest.log](https://github.com/user-attachments/files/17350591/latest.log)

**Comment by ryankshah** [comment]
Skyrimcraft already has the dragonshouts, so remove the dragonshouts mod and it will work fine!
