### ISSUE TITLE
Crash on world creation - Fabric 1.21

### ISSUE THREAD

**Issue by Morizera** [ryankshah/skyrimcraft-multiloader#3]
Cannot create a survival world, the game freezes and closes and then this error message appears:

![image](https://github.com/user-attachments/assets/aed7fa68-c56f-44f8-acbb-d6edf8dcf0f6)

My modlist and logs are in below:

![image](https://github.com/user-attachments/assets/a0a7e8c8-83ca-4b4c-947a-06e78e92b28b)
[crash-2024-10-12_13.35.43-server.txt](https://github.com/user-attachments/files/17350760/crash-2024-10-12_13.35.43-server.txt)
[latest.log](https://github.com/user-attachments/files/17350761/latest.log)

**Comment by ryankshah** [comment]
Version 0.3.1 of the mod was just released which fixes this bug and many others! - https://modrinth.com/mod/the-ender-scrolls-skyrimcraft/

**Comment by Morizera** [comment]
Thanks so much, you are really fast with the updates
